services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=mongodb://admin:password@mongo:27017/vedicdb?authSource=admin
      - JWT_SECRET=prod_jwt_secret_key_change_in_production
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:3000

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo:7
    restart: always
    # No ports exposed - only accessible within Docker network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    # No ports exposed - only accessible within Docker network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
  mongodb:
