services:
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=mongodb://admin:password@mongo:27017/vedicdb?authSource=admin
      - JWT_SECRET=dev_jwt_secret_key
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    restart: always
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WDS_SOCKET_HOST=localhost
      - FAST_REFRESH=true
      - REACT_APP_FAST_REFRESH=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_dev:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
  mongodb_dev: 