const BASE_URL = "/assets";

export const PLACEHOLDER_IMG = {
  COLLECT_FEE: `${BASE_URL}/images/placeholder/collect_fee.png`,
  NO_PATIENTS_ALIGN: `${BASE_URL}/images/placeholder/no_patients_align.png`,
  SEARCH_PATIENT: `${BASE_URL}/images/placeholder/search_patient.png`,
  NO_STAFF: `${BASE_URL}/images/placeholder/no_staff.png`,
  NO_ROLES: `${BASE_URL}/images/placeholder/no_rolls.png`,
  AUTH_WIDGETS: `${BASE_URL}/images/auth-widgets.png`,
  NO_CLINIC: `${BASE_URL}/images/placeholder/no_clinic.png`,
  NO_ORG: `${BASE_URL}/images/placeholder/no_org.png`,
  NO_MOUDLE: `${BASE_URL}/images/placeholder/no_module.png`,
};

export const AVATAR_IMG = {
  MALE: `${BASE_URL}/images/avatar/male.png`,
  FEMALE: `${BASE_URL}/images/avatar/female.png`,
  OTHER: `${BASE_URL}/images/avatar/other.png`,
};

export const ICON_NAME = {
  DASHBOARD: "akar-icons:dashboard",
  STAFF_MEETING:"tdesign:user-time",
  PATIENT: "material-symbols:outpatient-med-outline-rounded",
  WAITLIST: "fluent-mdl2:waitlist-confirm",
  TEAMS: "fluent:people-team-20-regular",
  MANAGEMENT: "carbon:id-management",
  MASTER: "hugeicons:master-card",
  ROLE: "eos-icons:role-binding-outlined",
  CLINIC: "healthicons:ambulatory-clinic-outline-24px",
  DISEASE:"fa7-solid:disease",
  SPECS:"icon-park-twotone:category-management",
  SEARCH_DUOTONE: "lets-icons:search-duotone",
  ADD_NEW: "basil:add-solid",
  ADD_CHAT: "fluent-color:chat-add-28",
  INFORMATION: "fluent-emoji:information",
  CONTACTS: "flat-color-icons:contacts",
  ADDRESS_BOOK: "flat-color-icons:address-book",
  GENDER: "streamline-ultimate-color:gender-hetero",
  AGENTS: "fluent-color:agents-48",
  LINK_OUT: "quill:link-out",
  EDIT: "tabler:edit",
  SUBMIT: "tabler:hand-click",
  CONSULT: "streamline-sharp:add-pdf-solid",
  ANGLE_RIGHT: "pepicons-print:angle-right",
  ANGLE_DOWN: "pepicons-print:angle-down",
  ARROW_RIGHT: "pepicons-print:arrow-right",
  BACK_MARK: "icon-park-twotone:back",
  VERTICAL_MENU: "iconamoon:menu-kebab-vertical-circle-light",
  HUMBURGER_OPEN: "mdi:hamburger-open",
  HUMBURGER_CLOSE: "charm:menu-hamburger",
  CLOSE_ONE: "icon-park-twotone:close-one",
  EYE_OFF_LINE: "majesticons:eye-off-line",
  EYE_OUTLINE: "ion:eye-outline",
  DOC_ADD: "icon-park:doc-add",
  HOME: "mdi:home-outline",
  LOGOUT: "ri:logout-circle-r-line",
  MOVE: "icon-park-twotone:move",
  DELETE: "icon-park-twotone:delete",
  PUBLISH: "ic:twotone-publish",
  UPDATE: "mdi:update",
  MODULE: "streamline-plump-color:module",
  NAV_MODULE: "streamline-sharp:module",
  SUB_MODULE: "streamline-color:module-three",
  ORG: "tabler:spaces",
  SECURITY: "ic:twotone-security"
}