const MESSAGES = {
  REGISTRATION_FAILED: "Registration failed. Please try again later",
  LOGIN_FAILED: "Login failed. Please try again later",
  AUTH_CHECK_FAILED: "Authentication check failed",
  RESOURCE_EXISTS: "Resource already exists",
  VALIDATION_FAILED: "Validation failed",
  GENERIC_ERROR: "Error",
  JWT_SECRET_MISSING: "JWT_SECRET_KEY is not defined in environment variables",
  ROLE_NAME_REQUIRED: "Role name is required",
  UNABLE_TO_FETCH_STAFF: "Unable to fetch staff list",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  CASE_ID_REQUIRED: "caseId is required",
  ALIGN_PATIENT_ID_STATUS_REQUIRED: "alignPatientId and status are required",
  PATIENT_REGISTERED: "Patient registered successfully",
  PATIENT_REGISTER_FAILED: "Failed to register patient",
  NO_PATIENTS_FOUND: "No patients found",
  PATIENT_SEARCH_FAILED: "Failed to search patients",
  PATIENT_NOT_FOUND: "Patient not found",
  PATIENT_VALIDATE_FAILED: "Failed to validate patient",
  PATIENT_ASSIGNED: "Patient assigned successfully",
  PATIENT_ASSIGN_FAILED: "Failed to assign patient",
  FETCH_ALIGN_PATIENT_LIST_FAILED: "Failed to fetch align patient list",
  STAFF_PROFILE_CREATED: "Staff profile created successfully",
  STAFF_PROFILE_UPDATED: "Staff profile updated successfully",
  STAFF_PROFILE_NOT_FOUND: "Staff Profile Not Found",
  USER_NOT_FOUND: "User Not Found",
  ROLE_NOT_FOUND: "Role Not Found",
  NO_STAFF_FOR_ROLE: "No staff found for the given role",
  INVALID_CREDENTIALS: "Invalid Credentials",
  TOKEN_GENERATION_FAILED: "Token Generation Failed",
  LOGIN_SUCCESSFUL: "Login Successful",
  ROLE_CREATED: "Role created successfully",
  ROLE_UPDATED: "Role updated successfully",
  ROLE_NOT_FOUND_GENERIC: "Role not found",
  PERMISSIONS_UPDATED: "Permissions updated successfully",
  ALIGN_PATIENT_NOT_FOUND: "Align patient not found",
  STATUS_UPDATED: "Status updated successfully",
  FAILED_TO_UPDATE_STATUS: "Failed to update status",

  // Label Formatter
  NOT_FOUND_MSG: "{label} Not Found.",
  CREATE: "{label} created successfully",
  UPDATE: "{label} updated successfully",
};

export default MESSAGES; 